"""HTML report generation for splitsmith."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .types import LeakageReport
from .audit import audit_cv_summary


def _severity_order(finding):
    order = {"error": 0, "warn": 1, "info": 2}
    return order.get(finding.severity, 3)


def _badge(severity: str) -> str:
    icons = {"error": "&#x1F534;", "warn": "&#x1F7E1;", "info": "&#x1F535;"}
    return icons.get(severity, "")


def _card_style(severity: str) -> str:
    styles = {
        "error": "border-left:4px solid #dc2626;background:#fef2f2;",
        "warn": "border-left:4px solid #d97706;background:#fffbeb;",
        "info": "border-left:4px solid #2563eb;background:#eff6ff;",
    }
    return styles.get(severity, "")


def _render_evidence(evidence: dict) -> str:
    if not evidence:
        return ""
    try:
        formatted = json.dumps(evidence, indent=2, default=str)
    except (TypeError, ValueError):
        formatted = str(evidence)
    return f'<pre style="background:#f1f5f9;padding:8px;border-radius:4px;font-size:13px;overflow-x:auto;">{formatted}</pre>'


def _finding_html(finding) -> str:
    return f'''<div style="padding:12px 16px;margin-bottom:10px;border-radius:6px;{_card_style(finding.severity)}">
<div style="font-weight:600;margin-bottom:4px;">{_badge(finding.severity)} {finding.title}</div>
<div style="color:#374151;font-size:14px;margin-bottom:6px;">{finding.details}</div>
{_render_evidence(finding.evidence)}
</div>'''


def _html_skeleton(title: str, body: str) -> str:
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f8f9fa;margin:0;padding:20px;color:#1f2937;}}
.container{{max-width:800px;margin:0 auto;}}
h1{{font-size:22px;margin-bottom:4px;}}
.badge{{display:inline-block;padding:4px 12px;border-radius:12px;font-weight:700;font-size:14px;color:#fff;}}
.pass{{background:#16a34a;}}.fail{{background:#dc2626;}}
.summary-bar{{display:flex;gap:16px;margin:16px 0;font-size:14px;}}
.summary-item{{padding:6px 12px;border-radius:6px;font-weight:600;}}
footer{{margin-top:30px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;}}
</style>
</head>
<body>
<div class="container">
{body}
</div>
</body>
</html>'''


def report_to_html(
    report: LeakageReport,
    title: str = "Splitsmith Leakage Report",
    path: Optional[str] = None,
) -> str:
    """Generate a self-contained HTML report from a LeakageReport."""
    if not isinstance(report, LeakageReport):
        raise TypeError("report must be a LeakageReport")

    now = datetime.now().isoformat(timespec="seconds")
    counts = report.summary()
    status = "PASS" if report.ok else "FAIL"
    badge_cls = "pass" if report.ok else "fail"

    sorted_findings = sorted(report.findings, key=_severity_order)
    findings_html = "\n".join(_finding_html(f) for f in sorted_findings)

    body = f'''<h1>{title}</h1>
<p style="color:#6b7280;font-size:14px;">{now}</p>
<p><span class="badge {badge_cls}">{status}</span></p>
<div class="summary-bar">
<span class="summary-item" style="background:#fee2e2;color:#dc2626;">{counts["error"]} error(s)</span>
<span class="summary-item" style="background:#fef3c7;color:#d97706;">{counts["warn"]} warning(s)</span>
<span class="summary-item" style="background:#dbeafe;color:#2563eb;">{counts["info"]} info</span>
</div>
<h2 style="font-size:18px;">Findings</h2>
{findings_html}
<footer>Generated by splitsmith &middot; {now}</footer>'''

    html = _html_skeleton(title, body)
    if path is not None:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="") as fh:
            fh.write(html)
    return html


def audit_cv_to_html(
    reports: List[LeakageReport],
    title: str = "Splitsmith CV Audit Report",
    path: Optional[str] = None,
) -> str:
    """Generate a self-contained HTML report from CV audit results."""
    if not isinstance(reports, list):
        raise TypeError("reports must be a list of LeakageReport")

    now = datetime.now().isoformat(timespec="seconds")
    summary = audit_cv_summary(reports)
    status = "PASS" if summary["all_ok"] else "FAIL"
    badge_cls = "pass" if summary["all_ok"] else "fail"

    folds_html = ""
    for i, r in enumerate(reports):
        c = r.summary()
        fold_status = "&#x2705;" if r.ok else "&#x274C;"
        sorted_findings = sorted(r.findings, key=_severity_order)
        findings_html = "\n".join(_finding_html(f) for f in sorted_findings)
        folds_html += f'''<details style="margin-bottom:12px;">
<summary style="cursor:pointer;font-weight:600;font-size:15px;padding:8px 0;">
{fold_status} Fold {i} &mdash; {c["error"]} error, {c["warn"]} warn, {c["info"]} info
</summary>
<div style="padding:8px 0 8px 12px;">
{findings_html}
</div>
</details>'''

    body = f'''<h1>{title}</h1>
<p style="color:#6b7280;font-size:14px;">{now}</p>
<p><span class="badge {badge_cls}">{status}</span></p>
<div class="summary-bar">
<span class="summary-item" style="background:#dbeafe;color:#2563eb;">{summary["n_folds"]} folds</span>
<span class="summary-item" style="background:#fee2e2;color:#dc2626;">{summary["total_errors"]} total error(s)</span>
<span class="summary-item" style="background:#fef3c7;color:#d97706;">{summary["total_warnings"]} total warning(s)</span>
</div>
<h2 style="font-size:18px;">Per-Fold Results</h2>
{folds_html}
<footer>Generated by splitsmith &middot; {now}</footer>'''

    html = _html_skeleton(title, body)
    if path is not None:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="") as fh:
            fh.write(html)
    return html
